name        : gmp
version     : 5.1.2
release     : 5
source      :
    - http://ftp.gnu.org/gnu/gmp/gmp-5.1.2.tar.xz : c7d943a6eceb4f0d3d3ab1176aec37853831cdfa281e012f8a344ba3ceefcbc2
homepage    : http://gnu.org/
license     :
    - GPL-3.0
summary     : The GMP package contains math libraries. These have useful functions for arbitrary precision arithmetic. 
description : |
    The GMP package contains math libraries. These have useful functions for arbitrary precision arithmetic.
emul32     : yes
devel      : yes
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        ABI=32 %configure --prefix=/usr --enable-cxx
    else
        %configure --prefix=/usr --enable-cxx
    fi
build      : |
    %make
install    : |
    %make_install
    %make distclean
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        mv -v $installdir/usr/include/gmp{,-32}.h
    else
        mv -v $installdir/usr/include/gmp{,-64}.h
        install -m 00644 $pkgfiles/gmp.h $installdir/usr/include/gmp.h
    fi
