name       : gmp
version    : 6.1.2
release    : 10
source     :
    - https://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.xz : 87b565e89a9a684fe4ebeeddb8399dce2599f9c9049854ca8c0dfbdea0e21912
homepage   : http://gnu.org/
license    :
    - GPL-3.0
summary    : The GMP package contains math libraries. These have useful functions for arbitrary precision arithmetic.
description: |
    The GMP package contains math libraries. These have useful functions for arbitrary precision arithmetic.
emul32     : yes
devel      : yes
component  : system.base
setup      : |
    # Help with musl builds
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        ABI=32 %configure --prefix=/usr --enable-cxx
    else
        %configure --prefix=/usr --enable-cxx
    fi
build      : |
    %make
install    : |
    %make_install
    %make distclean
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        mv -v $installdir/usr/include/gmp{,-32}.h
    else
        mv -v $installdir/usr/include/gmp{,-64}.h
        install -m 00644 $pkgfiles/gmp.h $installdir/usr/include/gmp.h
        install -D -d -m 00755 $installdir/usr/include/musl
        for i in $installdir/usr/include/gmp*.h ; do
            ln -sv ../$(basename $i) $installdir/usr/include/musl/.
        done
    fi
