name       : gmp
version    : 6.2.1
release    : 14
source     :
    - https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.xz : fd4829912cddd12f84181c3451cc752be224643e87fac497b69edddadc49b4f2
homepage   : http://gnu.org/
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
summary    : The GMP package contains math libraries. These have useful functions for arbitrary precision arithmetic.
description: |
    The GMP package contains math libraries. These have useful functions for arbitrary precision arithmetic.
emul32     : yes
devel      : yes
component  : system.base
setup      : |
    # Help with musl builds
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        ABI=32 %configure --prefix=/usr --enable-cxx --enable-fat
    else
        %configure --prefix=/usr --enable-cxx --enable-fat
    fi
build      : |
    %make
install    : |
    %make_install
    %make distclean
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        mv -v $installdir/usr/include/gmp{,-32}.h
    else
        mv -v $installdir/usr/include/gmp{,-64}.h
        install -m 00644 $pkgfiles/gmp.h $installdir/usr/include/gmp.h
        install -D -d -m 00755 $installdir/usr/include/musl
        for i in $installdir/usr/include/gmp*.h ; do
            ln -sv ../$(basename $i) $installdir/usr/include/musl/.
        done
    fi
